/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppRecordRouteImport } from './routes/_app/record'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppWorkSessionsRouteImport } from './routes/_app/work-sessions'
import { Route as DevUiRouteImport } from './routes/dev.ui'
import { Route as AppAIdRouteImport } from './routes/_app/a/$id'
import { Route as AppAnimalsIndexRouteImport } from './routes/_app/animals/index'
import { Route as AppAnimalsLabelsRouteImport } from './routes/_app/animals/labels'
import { Route as AppAnimalsNewRouteImport } from './routes/_app/animals/new'
import { Route as AppFinanceIndexRouteImport } from './routes/_app/finance/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppReportsBirthsRouteImport } from './routes/_app/reports/births'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsArchivedRouteImport } from './routes/_app/settings/archived'
import { Route as AppSettingsFarmRouteImport } from './routes/_app/settings/farm'
import { Route as AppSettingsImportRouteImport } from './routes/_app/settings/import'
import { Route as AppVaccinationsBulkRouteImport } from './routes/_app/vaccinations/bulk'
import { Route as AppWeightsImportRouteImport } from './routes/_app/weights/import'
import { Route as AppAnimalsIdIndexRouteImport } from './routes/_app/animals/$id/index'
import { Route as AppAnimalsIdAbortionRouteImport } from './routes/_app/animals/$id/abortion'
import { Route as AppAnimalsIdCalvingRouteImport } from './routes/_app/animals/$id/calving'
import { Route as AppAnimalsIdDiagnosisRouteImport } from './routes/_app/animals/$id/diagnosis'
import { Route as AppAnimalsIdEditRouteImport } from './routes/_app/animals/$id/edit'
import { Route as AppAnimalsIdServiceRouteImport } from './routes/_app/animals/$id/service'
import { Route as AppAnimalsIdTreatmentRouteImport } from './routes/_app/animals/$id/treatment'
import { Route as AppAnimalsIdVaccinationRouteImport } from './routes/_app/animals/$id/vaccination'
import { Route as AppAnimalsIdWeightRouteImport } from './routes/_app/animals/$id/weight'
import { Route as AppFinanceExpensesNewRouteImport } from './routes/_app/finance/expenses/new'
import { Route as AppSettingsBreedsIndexRouteImport } from './routes/_app/settings/breeds/index'
import { Route as AppSettingsBreedsIdRouteImport } from './routes/_app/settings/breeds/$id'
import { Route as AppSettingsBreedsNewRouteImport } from './routes/_app/settings/breeds/new'
import { Route as AppSettingsCyclesIndexRouteImport } from './routes/_app/settings/cycles/index'
import { Route as AppSettingsCyclesIdRouteImport } from './routes/_app/settings/cycles/$id'
import { Route as AppSettingsCyclesNewRouteImport } from './routes/_app/settings/cycles/new'
import { Route as AppSettingsLotsIndexRouteImport } from './routes/_app/settings/lots/index'
import { Route as AppSettingsLotsIdRouteImport } from './routes/_app/settings/lots/$id'
import { Route as AppSettingsLotsNewRouteImport } from './routes/_app/settings/lots/new'
import { Route as AppSettingsTagsIndexRouteImport } from './routes/_app/settings/tags/index'
import { Route as AppSettingsTagsIdRouteImport } from './routes/_app/settings/tags/$id'
import { Route as AppSettingsTagsNewRouteImport } from './routes/_app/settings/tags/new'
import { Route as AppSettingsUsersIndexRouteImport } from './routes/_app/settings/users/index'
import { Route as AppSettingsUsersIdRouteImport } from './routes/_app/settings/users/$id'
import { Route as AppSettingsUsersNewRouteImport } from './routes/_app/settings/users/new'
import { Route as AppSettingsVaccinesIndexRouteImport } from './routes/_app/settings/vaccines/index'
import { Route as AppSettingsVaccinesIdRouteImport } from './routes/_app/settings/vaccines/$id'
import { Route as AppSettingsVaccinesNewRouteImport } from './routes/_app/settings/vaccines/new'
import { Route as AppFinanceExpensesIdIndexRouteImport } from './routes/_app/finance/expenses/$id/index'
import { Route as AppFinanceExpensesIdEditRouteImport } from './routes/_app/finance/expenses/$id/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordRoute = AppRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkSessionsRoute = AppWorkSessionsRouteImport.update({
  id: '/work-sessions',
  path: '/work-sessions',
  getParentRoute: () => AppRoute,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAIdRoute = AppAIdRouteImport.update({
  id: '/a/$id',
  path: '/a/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIndexRoute = AppAnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsLabelsRoute = AppAnimalsLabelsRouteImport.update({
  id: '/animals/labels',
  path: '/animals/labels',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsNewRoute = AppAnimalsNewRouteImport.update({
  id: '/animals/new',
  path: '/animals/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsBirthsRoute = AppReportsBirthsRouteImport.update({
  id: '/reports/births',
  path: '/reports/births',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsArchivedRoute = AppSettingsArchivedRouteImport.update({
  id: '/settings/archived',
  path: '/settings/archived',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsFarmRoute = AppSettingsFarmRouteImport.update({
  id: '/settings/farm',
  path: '/settings/farm',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsImportRoute = AppSettingsImportRouteImport.update({
  id: '/settings/import',
  path: '/settings/import',
  getParentRoute: () => AppRoute,
} as any)
const AppVaccinationsBulkRoute = AppVaccinationsBulkRouteImport.update({
  id: '/vaccinations/bulk',
  path: '/vaccinations/bulk',
  getParentRoute: () => AppRoute,
} as any)
const AppWeightsImportRoute = AppWeightsImportRouteImport.update({
  id: '/weights/import',
  path: '/weights/import',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdIndexRoute = AppAnimalsIdIndexRouteImport.update({
  id: '/animals/$id/',
  path: '/animals/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdAbortionRoute = AppAnimalsIdAbortionRouteImport.update({
  id: '/animals/$id/abortion',
  path: '/animals/$id/abortion',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdCalvingRoute = AppAnimalsIdCalvingRouteImport.update({
  id: '/animals/$id/calving',
  path: '/animals/$id/calving',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdDiagnosisRoute = AppAnimalsIdDiagnosisRouteImport.update({
  id: '/animals/$id/diagnosis',
  path: '/animals/$id/diagnosis',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdEditRoute = AppAnimalsIdEditRouteImport.update({
  id: '/animals/$id/edit',
  path: '/animals/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdServiceRoute = AppAnimalsIdServiceRouteImport.update({
  id: '/animals/$id/service',
  path: '/animals/$id/service',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdTreatmentRoute = AppAnimalsIdTreatmentRouteImport.update({
  id: '/animals/$id/treatment',
  path: '/animals/$id/treatment',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdVaccinationRoute = AppAnimalsIdVaccinationRouteImport.update({
  id: '/animals/$id/vaccination',
  path: '/animals/$id/vaccination',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdWeightRoute = AppAnimalsIdWeightRouteImport.update({
  id: '/animals/$id/weight',
  path: '/animals/$id/weight',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceExpensesNewRoute = AppFinanceExpensesNewRouteImport.update({
  id: '/finance/expenses/new',
  path: '/finance/expenses/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBreedsIndexRoute = AppSettingsBreedsIndexRouteImport.update({
  id: '/settings/breeds/',
  path: '/settings/breeds/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBreedsIdRoute = AppSettingsBreedsIdRouteImport.update({
  id: '/settings/breeds/$id',
  path: '/settings/breeds/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBreedsNewRoute = AppSettingsBreedsNewRouteImport.update({
  id: '/settings/breeds/new',
  path: '/settings/breeds/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCyclesIndexRoute = AppSettingsCyclesIndexRouteImport.update({
  id: '/settings/cycles/',
  path: '/settings/cycles/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCyclesIdRoute = AppSettingsCyclesIdRouteImport.update({
  id: '/settings/cycles/$id',
  path: '/settings/cycles/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCyclesNewRoute = AppSettingsCyclesNewRouteImport.update({
  id: '/settings/cycles/new',
  path: '/settings/cycles/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLotsIndexRoute = AppSettingsLotsIndexRouteImport.update({
  id: '/settings/lots/',
  path: '/settings/lots/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLotsIdRoute = AppSettingsLotsIdRouteImport.update({
  id: '/settings/lots/$id',
  path: '/settings/lots/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLotsNewRoute = AppSettingsLotsNewRouteImport.update({
  id: '/settings/lots/new',
  path: '/settings/lots/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTagsIndexRoute = AppSettingsTagsIndexRouteImport.update({
  id: '/settings/tags/',
  path: '/settings/tags/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTagsIdRoute = AppSettingsTagsIdRouteImport.update({
  id: '/settings/tags/$id',
  path: '/settings/tags/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTagsNewRoute = AppSettingsTagsNewRouteImport.update({
  id: '/settings/tags/new',
  path: '/settings/tags/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersIndexRoute = AppSettingsUsersIndexRouteImport.update({
  id: '/settings/users/',
  path: '/settings/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersIdRoute = AppSettingsUsersIdRouteImport.update({
  id: '/settings/users/$id',
  path: '/settings/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersNewRoute = AppSettingsUsersNewRouteImport.update({
  id: '/settings/users/new',
  path: '/settings/users/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsVaccinesIndexRoute =
  AppSettingsVaccinesIndexRouteImport.update({
    id: '/settings/vaccines/',
    path: '/settings/vaccines/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsVaccinesIdRoute = AppSettingsVaccinesIdRouteImport.update({
  id: '/settings/vaccines/$id',
  path: '/settings/vaccines/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsVaccinesNewRoute = AppSettingsVaccinesNewRouteImport.update({
  id: '/settings/vaccines/new',
  path: '/settings/vaccines/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceExpensesIdIndexRoute =
  AppFinanceExpensesIdIndexRouteImport.update({
    id: '/finance/expenses/$id/',
    path: '/finance/expenses/$id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceExpensesIdEditRoute =
  AppFinanceExpensesIdEditRouteImport.update({
    id: '/finance/expenses/$id/edit',
    path: '/finance/expenses/$id/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/alerts': typeof AppAlertsRoute
  '/more': typeof AppMoreRoute
  '/record': typeof AppRecordRoute
  '/search': typeof AppSearchRoute
  '/work-sessions': typeof AppWorkSessionsRoute
  '/dev/ui': typeof DevUiRoute
  '/a/$id': typeof AppAIdRoute
  '/animals/labels': typeof AppAnimalsLabelsRoute
  '/animals/new': typeof AppAnimalsNewRoute
  '/reports/births': typeof AppReportsBirthsRoute
  '/settings/archived': typeof AppSettingsArchivedRoute
  '/settings/farm': typeof AppSettingsFarmRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/vaccinations/bulk': typeof AppVaccinationsBulkRoute
  '/weights/import': typeof AppWeightsImportRoute
  '/animals/': typeof AppAnimalsIndexRoute
  '/finance/': typeof AppFinanceIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/animals/$id/abortion': typeof AppAnimalsIdAbortionRoute
  '/animals/$id/calving': typeof AppAnimalsIdCalvingRoute
  '/animals/$id/diagnosis': typeof AppAnimalsIdDiagnosisRoute
  '/animals/$id/edit': typeof AppAnimalsIdEditRoute
  '/animals/$id/service': typeof AppAnimalsIdServiceRoute
  '/animals/$id/treatment': typeof AppAnimalsIdTreatmentRoute
  '/animals/$id/vaccination': typeof AppAnimalsIdVaccinationRoute
  '/animals/$id/weight': typeof AppAnimalsIdWeightRoute
  '/finance/expenses/new': typeof AppFinanceExpensesNewRoute
  '/settings/breeds/$id': typeof AppSettingsBreedsIdRoute
  '/settings/breeds/new': typeof AppSettingsBreedsNewRoute
  '/settings/cycles/$id': typeof AppSettingsCyclesIdRoute
  '/settings/cycles/new': typeof AppSettingsCyclesNewRoute
  '/settings/lots/$id': typeof AppSettingsLotsIdRoute
  '/settings/lots/new': typeof AppSettingsLotsNewRoute
  '/settings/tags/$id': typeof AppSettingsTagsIdRoute
  '/settings/tags/new': typeof AppSettingsTagsNewRoute
  '/settings/users/$id': typeof AppSettingsUsersIdRoute
  '/settings/users/new': typeof AppSettingsUsersNewRoute
  '/settings/vaccines/$id': typeof AppSettingsVaccinesIdRoute
  '/settings/vaccines/new': typeof AppSettingsVaccinesNewRoute
  '/animals/$id/': typeof AppAnimalsIdIndexRoute
  '/settings/breeds/': typeof AppSettingsBreedsIndexRoute
  '/settings/cycles/': typeof AppSettingsCyclesIndexRoute
  '/settings/lots/': typeof AppSettingsLotsIndexRoute
  '/settings/tags/': typeof AppSettingsTagsIndexRoute
  '/settings/users/': typeof AppSettingsUsersIndexRoute
  '/settings/vaccines/': typeof AppSettingsVaccinesIndexRoute
  '/finance/expenses/$id/edit': typeof AppFinanceExpensesIdEditRoute
  '/finance/expenses/$id/': typeof AppFinanceExpensesIdIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/alerts': typeof AppAlertsRoute
  '/more': typeof AppMoreRoute
  '/record': typeof AppRecordRoute
  '/search': typeof AppSearchRoute
  '/work-sessions': typeof AppWorkSessionsRoute
  '/dev/ui': typeof DevUiRoute
  '/': typeof AppIndexRoute
  '/a/$id': typeof AppAIdRoute
  '/animals/labels': typeof AppAnimalsLabelsRoute
  '/animals/new': typeof AppAnimalsNewRoute
  '/reports/births': typeof AppReportsBirthsRoute
  '/settings/archived': typeof AppSettingsArchivedRoute
  '/settings/farm': typeof AppSettingsFarmRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/vaccinations/bulk': typeof AppVaccinationsBulkRoute
  '/weights/import': typeof AppWeightsImportRoute
  '/animals': typeof AppAnimalsIndexRoute
  '/finance': typeof AppFinanceIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/animals/$id/abortion': typeof AppAnimalsIdAbortionRoute
  '/animals/$id/calving': typeof AppAnimalsIdCalvingRoute
  '/animals/$id/diagnosis': typeof AppAnimalsIdDiagnosisRoute
  '/animals/$id/edit': typeof AppAnimalsIdEditRoute
  '/animals/$id/service': typeof AppAnimalsIdServiceRoute
  '/animals/$id/treatment': typeof AppAnimalsIdTreatmentRoute
  '/animals/$id/vaccination': typeof AppAnimalsIdVaccinationRoute
  '/animals/$id/weight': typeof AppAnimalsIdWeightRoute
  '/finance/expenses/new': typeof AppFinanceExpensesNewRoute
  '/settings/breeds/$id': typeof AppSettingsBreedsIdRoute
  '/settings/breeds/new': typeof AppSettingsBreedsNewRoute
  '/settings/cycles/$id': typeof AppSettingsCyclesIdRoute
  '/settings/cycles/new': typeof AppSettingsCyclesNewRoute
  '/settings/lots/$id': typeof AppSettingsLotsIdRoute
  '/settings/lots/new': typeof AppSettingsLotsNewRoute
  '/settings/tags/$id': typeof AppSettingsTagsIdRoute
  '/settings/tags/new': typeof AppSettingsTagsNewRoute
  '/settings/users/$id': typeof AppSettingsUsersIdRoute
  '/settings/users/new': typeof AppSettingsUsersNewRoute
  '/settings/vaccines/$id': typeof AppSettingsVaccinesIdRoute
  '/settings/vaccines/new': typeof AppSettingsVaccinesNewRoute
  '/animals/$id': typeof AppAnimalsIdIndexRoute
  '/settings/breeds': typeof AppSettingsBreedsIndexRoute
  '/settings/cycles': typeof AppSettingsCyclesIndexRoute
  '/settings/lots': typeof AppSettingsLotsIndexRoute
  '/settings/tags': typeof AppSettingsTagsIndexRoute
  '/settings/users': typeof AppSettingsUsersIndexRoute
  '/settings/vaccines': typeof AppSettingsVaccinesIndexRoute
  '/finance/expenses/$id/edit': typeof AppFinanceExpensesIdEditRoute
  '/finance/expenses/$id': typeof AppFinanceExpensesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/record': typeof AppRecordRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/work-sessions': typeof AppWorkSessionsRoute
  '/dev/ui': typeof DevUiRoute
  '/_app/': typeof AppIndexRoute
  '/_app/a/$id': typeof AppAIdRoute
  '/_app/animals/labels': typeof AppAnimalsLabelsRoute
  '/_app/animals/new': typeof AppAnimalsNewRoute
  '/_app/reports/births': typeof AppReportsBirthsRoute
  '/_app/settings/archived': typeof AppSettingsArchivedRoute
  '/_app/settings/farm': typeof AppSettingsFarmRoute
  '/_app/settings/import': typeof AppSettingsImportRoute
  '/_app/vaccinations/bulk': typeof AppVaccinationsBulkRoute
  '/_app/weights/import': typeof AppWeightsImportRoute
  '/_app/animals/': typeof AppAnimalsIndexRoute
  '/_app/finance/': typeof AppFinanceIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/animals/$id/abortion': typeof AppAnimalsIdAbortionRoute
  '/_app/animals/$id/calving': typeof AppAnimalsIdCalvingRoute
  '/_app/animals/$id/diagnosis': typeof AppAnimalsIdDiagnosisRoute
  '/_app/animals/$id/edit': typeof AppAnimalsIdEditRoute
  '/_app/animals/$id/service': typeof AppAnimalsIdServiceRoute
  '/_app/animals/$id/treatment': typeof AppAnimalsIdTreatmentRoute
  '/_app/animals/$id/vaccination': typeof AppAnimalsIdVaccinationRoute
  '/_app/animals/$id/weight': typeof AppAnimalsIdWeightRoute
  '/_app/finance/expenses/new': typeof AppFinanceExpensesNewRoute
  '/_app/settings/breeds/$id': typeof AppSettingsBreedsIdRoute
  '/_app/settings/breeds/new': typeof AppSettingsBreedsNewRoute
  '/_app/settings/cycles/$id': typeof AppSettingsCyclesIdRoute
  '/_app/settings/cycles/new': typeof AppSettingsCyclesNewRoute
  '/_app/settings/lots/$id': typeof AppSettingsLotsIdRoute
  '/_app/settings/lots/new': typeof AppSettingsLotsNewRoute
  '/_app/settings/tags/$id': typeof AppSettingsTagsIdRoute
  '/_app/settings/tags/new': typeof AppSettingsTagsNewRoute
  '/_app/settings/users/$id': typeof AppSettingsUsersIdRoute
  '/_app/settings/users/new': typeof AppSettingsUsersNewRoute
  '/_app/settings/vaccines/$id': typeof AppSettingsVaccinesIdRoute
  '/_app/settings/vaccines/new': typeof AppSettingsVaccinesNewRoute
  '/_app/animals/$id/': typeof AppAnimalsIdIndexRoute
  '/_app/settings/breeds/': typeof AppSettingsBreedsIndexRoute
  '/_app/settings/cycles/': typeof AppSettingsCyclesIndexRoute
  '/_app/settings/lots/': typeof AppSettingsLotsIndexRoute
  '/_app/settings/tags/': typeof AppSettingsTagsIndexRoute
  '/_app/settings/users/': typeof AppSettingsUsersIndexRoute
  '/_app/settings/vaccines/': typeof AppSettingsVaccinesIndexRoute
  '/_app/finance/expenses/$id/edit': typeof AppFinanceExpensesIdEditRoute
  '/_app/finance/expenses/$id/': typeof AppFinanceExpensesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/account'
    | '/alerts'
    | '/more'
    | '/record'
    | '/search'
    | '/work-sessions'
    | '/dev/ui'
    | '/a/$id'
    | '/animals/labels'
    | '/animals/new'
    | '/reports/births'
    | '/settings/archived'
    | '/settings/farm'
    | '/settings/import'
    | '/vaccinations/bulk'
    | '/weights/import'
    | '/animals/'
    | '/finance/'
    | '/reports/'
    | '/settings/'
    | '/animals/$id/abortion'
    | '/animals/$id/calving'
    | '/animals/$id/diagnosis'
    | '/animals/$id/edit'
    | '/animals/$id/service'
    | '/animals/$id/treatment'
    | '/animals/$id/vaccination'
    | '/animals/$id/weight'
    | '/finance/expenses/new'
    | '/settings/breeds/$id'
    | '/settings/breeds/new'
    | '/settings/cycles/$id'
    | '/settings/cycles/new'
    | '/settings/lots/$id'
    | '/settings/lots/new'
    | '/settings/tags/$id'
    | '/settings/tags/new'
    | '/settings/users/$id'
    | '/settings/users/new'
    | '/settings/vaccines/$id'
    | '/settings/vaccines/new'
    | '/animals/$id/'
    | '/settings/breeds/'
    | '/settings/cycles/'
    | '/settings/lots/'
    | '/settings/tags/'
    | '/settings/users/'
    | '/settings/vaccines/'
    | '/finance/expenses/$id/edit'
    | '/finance/expenses/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/account'
    | '/alerts'
    | '/more'
    | '/record'
    | '/search'
    | '/work-sessions'
    | '/dev/ui'
    | '/'
    | '/a/$id'
    | '/animals/labels'
    | '/animals/new'
    | '/reports/births'
    | '/settings/archived'
    | '/settings/farm'
    | '/settings/import'
    | '/vaccinations/bulk'
    | '/weights/import'
    | '/animals'
    | '/finance'
    | '/reports'
    | '/settings'
    | '/animals/$id/abortion'
    | '/animals/$id/calving'
    | '/animals/$id/diagnosis'
    | '/animals/$id/edit'
    | '/animals/$id/service'
    | '/animals/$id/treatment'
    | '/animals/$id/vaccination'
    | '/animals/$id/weight'
    | '/finance/expenses/new'
    | '/settings/breeds/$id'
    | '/settings/breeds/new'
    | '/settings/cycles/$id'
    | '/settings/cycles/new'
    | '/settings/lots/$id'
    | '/settings/lots/new'
    | '/settings/tags/$id'
    | '/settings/tags/new'
    | '/settings/users/$id'
    | '/settings/users/new'
    | '/settings/vaccines/$id'
    | '/settings/vaccines/new'
    | '/animals/$id'
    | '/settings/breeds'
    | '/settings/cycles'
    | '/settings/lots'
    | '/settings/tags'
    | '/settings/users'
    | '/settings/vaccines'
    | '/finance/expenses/$id/edit'
    | '/finance/expenses/$id'
  id:
    | '__root__'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/_app/account'
    | '/_app/alerts'
    | '/_app/more'
    | '/_app/record'
    | '/_app/search'
    | '/_app/work-sessions'
    | '/dev/ui'
    | '/_app/'
    | '/_app/a/$id'
    | '/_app/animals/labels'
    | '/_app/animals/new'
    | '/_app/reports/births'
    | '/_app/settings/archived'
    | '/_app/settings/farm'
    | '/_app/settings/import'
    | '/_app/vaccinations/bulk'
    | '/_app/weights/import'
    | '/_app/animals/'
    | '/_app/finance/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/animals/$id/abortion'
    | '/_app/animals/$id/calving'
    | '/_app/animals/$id/diagnosis'
    | '/_app/animals/$id/edit'
    | '/_app/animals/$id/service'
    | '/_app/animals/$id/treatment'
    | '/_app/animals/$id/vaccination'
    | '/_app/animals/$id/weight'
    | '/_app/finance/expenses/new'
    | '/_app/settings/breeds/$id'
    | '/_app/settings/breeds/new'
    | '/_app/settings/cycles/$id'
    | '/_app/settings/cycles/new'
    | '/_app/settings/lots/$id'
    | '/_app/settings/lots/new'
    | '/_app/settings/tags/$id'
    | '/_app/settings/tags/new'
    | '/_app/settings/users/$id'
    | '/_app/settings/users/new'
    | '/_app/settings/vaccines/$id'
    | '/_app/settings/vaccines/new'
    | '/_app/animals/$id/'
    | '/_app/settings/breeds/'
    | '/_app/settings/cycles/'
    | '/_app/settings/lots/'
    | '/_app/settings/tags/'
    | '/_app/settings/users/'
    | '/_app/settings/vaccines/'
    | '/_app/finance/expenses/$id/edit'
    | '/_app/finance/expenses/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  DevUiRoute: typeof DevUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/record': {
      id: '/_app/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AppRecordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-sessions': {
      id: '/_app/work-sessions'
      path: '/work-sessions'
      fullPath: '/work-sessions'
      preLoaderRoute: typeof AppWorkSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/a/$id': {
      id: '/_app/a/$id'
      path: '/a/$id'
      fullPath: '/a/$id'
      preLoaderRoute: typeof AppAIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/': {
      id: '/_app/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AppAnimalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/labels': {
      id: '/_app/animals/labels'
      path: '/animals/labels'
      fullPath: '/animals/labels'
      preLoaderRoute: typeof AppAnimalsLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/new': {
      id: '/_app/animals/new'
      path: '/animals/new'
      fullPath: '/animals/new'
      preLoaderRoute: typeof AppAnimalsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/': {
      id: '/_app/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/births': {
      id: '/_app/reports/births'
      path: '/reports/births'
      fullPath: '/reports/births'
      preLoaderRoute: typeof AppReportsBirthsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/archived': {
      id: '/_app/settings/archived'
      path: '/settings/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof AppSettingsArchivedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/farm': {
      id: '/_app/settings/farm'
      path: '/settings/farm'
      fullPath: '/settings/farm'
      preLoaderRoute: typeof AppSettingsFarmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/import': {
      id: '/_app/settings/import'
      path: '/settings/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof AppSettingsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vaccinations/bulk': {
      id: '/_app/vaccinations/bulk'
      path: '/vaccinations/bulk'
      fullPath: '/vaccinations/bulk'
      preLoaderRoute: typeof AppVaccinationsBulkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/weights/import': {
      id: '/_app/weights/import'
      path: '/weights/import'
      fullPath: '/weights/import'
      preLoaderRoute: typeof AppWeightsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id/': {
      id: '/_app/animals/$id/'
      path: '/animals/$id'
      fullPath: '/animals/$id/'
      preLoaderRoute: typeof AppAnimalsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id/abortion': {
      id: '/_app/animals/$id/abortion'
      path: '/animals/$id/abortion'
      fullPath: '/animals/$id/abortion'
      preLoaderRoute: typeof AppAnimalsIdAbortionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id/calving': {
      id: '/_app/animals/$id/calving'
      path: '/animals/$id/calving'
      fullPath: '/animals/$id/calving'
      preLoaderRoute: typeof AppAnimalsIdCalvingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id/diagnosis': {
      id: '/_app/animals/$id/diagnosis'
      path: '/animals/$id/diagnosis'
      fullPath: '/animals/$id/diagnosis'
      preLoaderRoute: typeof AppAnimalsIdDiagnosisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id/edit': {
      id: '/_app/animals/$id/edit'
      path: '/animals/$id/edit'
      fullPath: '/animals/$id/edit'
      preLoaderRoute: typeof AppAnimalsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id/service': {
      id: '/_app/animals/$id/service'
      path: '/animals/$id/service'
      fullPath: '/animals/$id/service'
      preLoaderRoute: typeof AppAnimalsIdServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id/treatment': {
      id: '/_app/animals/$id/treatment'
      path: '/animals/$id/treatment'
      fullPath: '/animals/$id/treatment'
      preLoaderRoute: typeof AppAnimalsIdTreatmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id/vaccination': {
      id: '/_app/animals/$id/vaccination'
      path: '/animals/$id/vaccination'
      fullPath: '/animals/$id/vaccination'
      preLoaderRoute: typeof AppAnimalsIdVaccinationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id/weight': {
      id: '/_app/animals/$id/weight'
      path: '/animals/$id/weight'
      fullPath: '/animals/$id/weight'
      preLoaderRoute: typeof AppAnimalsIdWeightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/expenses/new': {
      id: '/_app/finance/expenses/new'
      path: '/finance/expenses/new'
      fullPath: '/finance/expenses/new'
      preLoaderRoute: typeof AppFinanceExpensesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/breeds/': {
      id: '/_app/settings/breeds/'
      path: '/settings/breeds'
      fullPath: '/settings/breeds/'
      preLoaderRoute: typeof AppSettingsBreedsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/breeds/$id': {
      id: '/_app/settings/breeds/$id'
      path: '/settings/breeds/$id'
      fullPath: '/settings/breeds/$id'
      preLoaderRoute: typeof AppSettingsBreedsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/breeds/new': {
      id: '/_app/settings/breeds/new'
      path: '/settings/breeds/new'
      fullPath: '/settings/breeds/new'
      preLoaderRoute: typeof AppSettingsBreedsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/cycles/': {
      id: '/_app/settings/cycles/'
      path: '/settings/cycles'
      fullPath: '/settings/cycles/'
      preLoaderRoute: typeof AppSettingsCyclesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/cycles/$id': {
      id: '/_app/settings/cycles/$id'
      path: '/settings/cycles/$id'
      fullPath: '/settings/cycles/$id'
      preLoaderRoute: typeof AppSettingsCyclesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/cycles/new': {
      id: '/_app/settings/cycles/new'
      path: '/settings/cycles/new'
      fullPath: '/settings/cycles/new'
      preLoaderRoute: typeof AppSettingsCyclesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/lots/': {
      id: '/_app/settings/lots/'
      path: '/settings/lots'
      fullPath: '/settings/lots/'
      preLoaderRoute: typeof AppSettingsLotsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/lots/$id': {
      id: '/_app/settings/lots/$id'
      path: '/settings/lots/$id'
      fullPath: '/settings/lots/$id'
      preLoaderRoute: typeof AppSettingsLotsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/lots/new': {
      id: '/_app/settings/lots/new'
      path: '/settings/lots/new'
      fullPath: '/settings/lots/new'
      preLoaderRoute: typeof AppSettingsLotsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/tags/': {
      id: '/_app/settings/tags/'
      path: '/settings/tags'
      fullPath: '/settings/tags/'
      preLoaderRoute: typeof AppSettingsTagsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/tags/$id': {
      id: '/_app/settings/tags/$id'
      path: '/settings/tags/$id'
      fullPath: '/settings/tags/$id'
      preLoaderRoute: typeof AppSettingsTagsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/tags/new': {
      id: '/_app/settings/tags/new'
      path: '/settings/tags/new'
      fullPath: '/settings/tags/new'
      preLoaderRoute: typeof AppSettingsTagsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users/': {
      id: '/_app/settings/users/'
      path: '/settings/users'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof AppSettingsUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users/$id': {
      id: '/_app/settings/users/$id'
      path: '/settings/users/$id'
      fullPath: '/settings/users/$id'
      preLoaderRoute: typeof AppSettingsUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users/new': {
      id: '/_app/settings/users/new'
      path: '/settings/users/new'
      fullPath: '/settings/users/new'
      preLoaderRoute: typeof AppSettingsUsersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/vaccines/': {
      id: '/_app/settings/vaccines/'
      path: '/settings/vaccines'
      fullPath: '/settings/vaccines/'
      preLoaderRoute: typeof AppSettingsVaccinesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/vaccines/$id': {
      id: '/_app/settings/vaccines/$id'
      path: '/settings/vaccines/$id'
      fullPath: '/settings/vaccines/$id'
      preLoaderRoute: typeof AppSettingsVaccinesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/vaccines/new': {
      id: '/_app/settings/vaccines/new'
      path: '/settings/vaccines/new'
      fullPath: '/settings/vaccines/new'
      preLoaderRoute: typeof AppSettingsVaccinesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/expenses/$id/': {
      id: '/_app/finance/expenses/$id/'
      path: '/finance/expenses/$id'
      fullPath: '/finance/expenses/$id/'
      preLoaderRoute: typeof AppFinanceExpensesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/expenses/$id/edit': {
      id: '/_app/finance/expenses/$id/edit'
      path: '/finance/expenses/$id/edit'
      fullPath: '/finance/expenses/$id/edit'
      preLoaderRoute: typeof AppFinanceExpensesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppMoreRoute: typeof AppMoreRoute
  AppRecordRoute: typeof AppRecordRoute
  AppSearchRoute: typeof AppSearchRoute
  AppWorkSessionsRoute: typeof AppWorkSessionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAIdRoute: typeof AppAIdRoute
  AppAnimalsLabelsRoute: typeof AppAnimalsLabelsRoute
  AppAnimalsNewRoute: typeof AppAnimalsNewRoute
  AppReportsBirthsRoute: typeof AppReportsBirthsRoute
  AppSettingsArchivedRoute: typeof AppSettingsArchivedRoute
  AppSettingsFarmRoute: typeof AppSettingsFarmRoute
  AppSettingsImportRoute: typeof AppSettingsImportRoute
  AppVaccinationsBulkRoute: typeof AppVaccinationsBulkRoute
  AppWeightsImportRoute: typeof AppWeightsImportRoute
  AppAnimalsIndexRoute: typeof AppAnimalsIndexRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppAnimalsIdAbortionRoute: typeof AppAnimalsIdAbortionRoute
  AppAnimalsIdCalvingRoute: typeof AppAnimalsIdCalvingRoute
  AppAnimalsIdDiagnosisRoute: typeof AppAnimalsIdDiagnosisRoute
  AppAnimalsIdEditRoute: typeof AppAnimalsIdEditRoute
  AppAnimalsIdServiceRoute: typeof AppAnimalsIdServiceRoute
  AppAnimalsIdTreatmentRoute: typeof AppAnimalsIdTreatmentRoute
  AppAnimalsIdVaccinationRoute: typeof AppAnimalsIdVaccinationRoute
  AppAnimalsIdWeightRoute: typeof AppAnimalsIdWeightRoute
  AppFinanceExpensesNewRoute: typeof AppFinanceExpensesNewRoute
  AppSettingsBreedsIdRoute: typeof AppSettingsBreedsIdRoute
  AppSettingsBreedsNewRoute: typeof AppSettingsBreedsNewRoute
  AppSettingsCyclesIdRoute: typeof AppSettingsCyclesIdRoute
  AppSettingsCyclesNewRoute: typeof AppSettingsCyclesNewRoute
  AppSettingsLotsIdRoute: typeof AppSettingsLotsIdRoute
  AppSettingsLotsNewRoute: typeof AppSettingsLotsNewRoute
  AppSettingsTagsIdRoute: typeof AppSettingsTagsIdRoute
  AppSettingsTagsNewRoute: typeof AppSettingsTagsNewRoute
  AppSettingsUsersIdRoute: typeof AppSettingsUsersIdRoute
  AppSettingsUsersNewRoute: typeof AppSettingsUsersNewRoute
  AppSettingsVaccinesIdRoute: typeof AppSettingsVaccinesIdRoute
  AppSettingsVaccinesNewRoute: typeof AppSettingsVaccinesNewRoute
  AppAnimalsIdIndexRoute: typeof AppAnimalsIdIndexRoute
  AppSettingsBreedsIndexRoute: typeof AppSettingsBreedsIndexRoute
  AppSettingsCyclesIndexRoute: typeof AppSettingsCyclesIndexRoute
  AppSettingsLotsIndexRoute: typeof AppSettingsLotsIndexRoute
  AppSettingsTagsIndexRoute: typeof AppSettingsTagsIndexRoute
  AppSettingsUsersIndexRoute: typeof AppSettingsUsersIndexRoute
  AppSettingsVaccinesIndexRoute: typeof AppSettingsVaccinesIndexRoute
  AppFinanceExpensesIdEditRoute: typeof AppFinanceExpensesIdEditRoute
  AppFinanceExpensesIdIndexRoute: typeof AppFinanceExpensesIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppMoreRoute: AppMoreRoute,
  AppRecordRoute: AppRecordRoute,
  AppSearchRoute: AppSearchRoute,
  AppWorkSessionsRoute: AppWorkSessionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAIdRoute: AppAIdRoute,
  AppAnimalsLabelsRoute: AppAnimalsLabelsRoute,
  AppAnimalsNewRoute: AppAnimalsNewRoute,
  AppReportsBirthsRoute: AppReportsBirthsRoute,
  AppSettingsArchivedRoute: AppSettingsArchivedRoute,
  AppSettingsFarmRoute: AppSettingsFarmRoute,
  AppSettingsImportRoute: AppSettingsImportRoute,
  AppVaccinationsBulkRoute: AppVaccinationsBulkRoute,
  AppWeightsImportRoute: AppWeightsImportRoute,
  AppAnimalsIndexRoute: AppAnimalsIndexRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppAnimalsIdAbortionRoute: AppAnimalsIdAbortionRoute,
  AppAnimalsIdCalvingRoute: AppAnimalsIdCalvingRoute,
  AppAnimalsIdDiagnosisRoute: AppAnimalsIdDiagnosisRoute,
  AppAnimalsIdEditRoute: AppAnimalsIdEditRoute,
  AppAnimalsIdServiceRoute: AppAnimalsIdServiceRoute,
  AppAnimalsIdTreatmentRoute: AppAnimalsIdTreatmentRoute,
  AppAnimalsIdVaccinationRoute: AppAnimalsIdVaccinationRoute,
  AppAnimalsIdWeightRoute: AppAnimalsIdWeightRoute,
  AppFinanceExpensesNewRoute: AppFinanceExpensesNewRoute,
  AppSettingsBreedsIdRoute: AppSettingsBreedsIdRoute,
  AppSettingsBreedsNewRoute: AppSettingsBreedsNewRoute,
  AppSettingsCyclesIdRoute: AppSettingsCyclesIdRoute,
  AppSettingsCyclesNewRoute: AppSettingsCyclesNewRoute,
  AppSettingsLotsIdRoute: AppSettingsLotsIdRoute,
  AppSettingsLotsNewRoute: AppSettingsLotsNewRoute,
  AppSettingsTagsIdRoute: AppSettingsTagsIdRoute,
  AppSettingsTagsNewRoute: AppSettingsTagsNewRoute,
  AppSettingsUsersIdRoute: AppSettingsUsersIdRoute,
  AppSettingsUsersNewRoute: AppSettingsUsersNewRoute,
  AppSettingsVaccinesIdRoute: AppSettingsVaccinesIdRoute,
  AppSettingsVaccinesNewRoute: AppSettingsVaccinesNewRoute,
  AppAnimalsIdIndexRoute: AppAnimalsIdIndexRoute,
  AppSettingsBreedsIndexRoute: AppSettingsBreedsIndexRoute,
  AppSettingsCyclesIndexRoute: AppSettingsCyclesIndexRoute,
  AppSettingsLotsIndexRoute: AppSettingsLotsIndexRoute,
  AppSettingsTagsIndexRoute: AppSettingsTagsIndexRoute,
  AppSettingsUsersIndexRoute: AppSettingsUsersIndexRoute,
  AppSettingsVaccinesIndexRoute: AppSettingsVaccinesIndexRoute,
  AppFinanceExpensesIdEditRoute: AppFinanceExpensesIdEditRoute,
  AppFinanceExpensesIdIndexRoute: AppFinanceExpensesIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  DevUiRoute: DevUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
